{
  imports = [
    ./core
    ./platform/darwin
    ./terminal/cli
    ./terminal/shell
    ./terminal/ghostty
    ./terminal/kitty
    ./development/languages
    ./development/tools
    ./development/nixvim
    ./development/zed
    ./development/vscode
    ./development/apple-container
    ./development/podman
    ./desktop/fonts
    ./desktop/theme
    ./desktop/applications
    ./desktop/winbox
    ./platform/nixos
  ];
}
